"""update models

Revision ID: 05bc7f1b2367
Revises: a50e4d13abf1
Create Date: 2026-03-01 15:45:48.014594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bc7f1b2367'
down_revision: Union[str, Sequence[str], None] = 'a50e4d13abf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('kyc_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='kycstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('savings_accounts',
    sa.Column('account_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('account_type', sa.Enum('REGULAR', 'SALARY', 'PREMIUM', name='accounttype'), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FROZEN', 'CLOSED', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_savings_accounts_account_id'), 'savings_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_savings_accounts_user_id'), 'savings_accounts', ['user_id'], unique=False)
    op.create_table('stock_holdings',
    sa.Column('holding_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('holding_id')
    )
    op.create_index(op.f('ix_stock_holdings_holding_id'), 'stock_holdings', ['holding_id'], unique=False)
    op.create_index(op.f('ix_stock_holdings_stock_symbol'), 'stock_holdings', ['stock_symbol'], unique=False)
    op.create_index(op.f('ix_stock_holdings_user_id'), 'stock_holdings', ['user_id'], unique=False)
    op.create_table('stock_transactions',
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_number', sa.String(length=30), nullable=False),
    sa.Column('stock_symbol', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='stocktransactiontype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'PENDING', 'FAILED', name='stocktransactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_stock_transactions_created_at'), 'stock_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_transactions_stock_symbol'), 'stock_transactions', ['stock_symbol'], unique=False)
    op.create_index(op.f('ix_stock_transactions_transaction_id'), 'stock_transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_transaction_number'), 'stock_transactions', ['transaction_number'], unique=True)
    op.create_index(op.f('ix_stock_transactions_user_id'), 'stock_transactions', ['user_id'], unique=False)
    op.create_table('fixed_deposits',
    sa.Column('fd_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('savings_account_id', sa.BigInteger(), nullable=False),
    sa.Column('fd_number', sa.String(length=20), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('maturity_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MATURED', 'CLOSED', name='fdstatus'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['savings_account_id'], ['savings_accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fd_id')
    )
    op.create_index(op.f('ix_fixed_deposits_fd_id'), 'fixed_deposits', ['fd_id'], unique=False)
    op.create_index(op.f('ix_fixed_deposits_fd_number'), 'fixed_deposits', ['fd_number'], unique=True)
    op.create_index(op.f('ix_fixed_deposits_maturity_date'), 'fixed_deposits', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_fixed_deposits_savings_account_id'), 'fixed_deposits', ['savings_account_id'], unique=False)
    op.create_index(op.f('ix_fixed_deposits_status'), 'fixed_deposits', ['status'], unique=False)
    op.create_index(op.f('ix_fixed_deposits_user_id'), 'fixed_deposits', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_number', sa.String(length=30), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'FD_CREATE', 'FD_MATURE', 'FD_CLOSE', 'STOCK_BUY', 'STOCK_SELL', 'INTEREST_CREDIT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', 'REVERSED', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['savings_accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_number'), 'transactions', ['transaction_number'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_fixed_deposits_user_id'), table_name='fixed_deposits')
    op.drop_index(op.f('ix_fixed_deposits_status'), table_name='fixed_deposits')
    op.drop_index(op.f('ix_fixed_deposits_savings_account_id'), table_name='fixed_deposits')
    op.drop_index(op.f('ix_fixed_deposits_maturity_date'), table_name='fixed_deposits')
    op.drop_index(op.f('ix_fixed_deposits_fd_number'), table_name='fixed_deposits')
    op.drop_index(op.f('ix_fixed_deposits_fd_id'), table_name='fixed_deposits')
    op.drop_table('fixed_deposits')
    op.drop_index(op.f('ix_stock_transactions_user_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_transaction_number'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_transaction_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_stock_symbol'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_created_at'), table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_index(op.f('ix_stock_holdings_user_id'), table_name='stock_holdings')
    op.drop_index(op.f('ix_stock_holdings_stock_symbol'), table_name='stock_holdings')
    op.drop_index(op.f('ix_stock_holdings_holding_id'), table_name='stock_holdings')
    op.drop_table('stock_holdings')
    op.drop_index(op.f('ix_savings_accounts_user_id'), table_name='savings_accounts')
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.drop_index(op.f('ix_savings_accounts_account_id'), table_name='savings_accounts')
    op.drop_table('savings_accounts')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
